<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Swift Mailing List Archive</title>
    <link rel="stylesheet" href="/css/app-13f065ae5e595562a5022c544e3b976c.css?vsn=d">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <img src="/images/swift-d0237fc716ba0932a940049990beba1b.svg?vsn=d" height="70">
      </header>

      <p class="alert alert-info" role="alert"></p>
      <p class="alert alert-danger" role="alert"></p>

    </div> <!-- /container -->
    <main role="main">
<div class="comment-wrapper"><ul class="comments"><li class="comment"><div class="avatar"><img src="https://www.gravatar.com/avatar/6dbccdb14c9594946a01d146877040c1?s=50"></div><header><strong>Default value for throwing closure argument of a rethrowing function</strong> from <string>bhargav gurlanka</string> &lt;bhargav.grlnk at gmail.com&gt;<p>May 16, 2016 at 03:00:00pm</p></header><div class="content"><p>Hi all,<br></p><p>Could someone please tell me why the following fails?<br></p><p>func foo(f: () throws -&gt; () = {}) rethrows {<br>    try f()<br>}<br></p><p>// Fine<br>foo({ })<br></p><p>// This fails with error:<br>//    call is to &#39;rethrows&#39; function,<br>//    but a defaulted argument function can throw<br>foo()<br></p><p>Why should I have to write &quot;try foo()&quot;, shouldn&#39;t it take the default value<br>(non throwing closure)?<br></p><p>Regards,<br>Bhargav Gurlanka<br>-------------- next part --------------<br>An HTML attachment was scrubbed...<br>URL: &lt;https://lists.swift.org/pipermail/swift-users/attachments/20160516/af1f444d/attachment.html&gt;<br></p></div><ul class="comments"><li class="comment"><div class="avatar"><img src="https://www.gravatar.com/avatar/06c1dcc7dce6a93d194b9c013376e3f0?s=50"></div><header><strong>Default value for throwing closure argument of a rethrowing function</strong> from <string>Joe Groff</string> &lt;jgroff at apple.com&gt;<p>May 16, 2016 at 10:00:00am</p></header><div class="content"><p>&gt; On May 16, 2016, at 2:35 AM, bhargav gurlanka via swift-users &lt;swift-users at swift.org&gt; wrote:<br>&gt; <br>&gt; Hi all,<br>&gt; <br>&gt; Could someone please tell me why the following fails?<br>&gt; <br>&gt; func foo(f: () throws -&gt; () = {}) rethrows {<br>&gt;     try f()<br>&gt; }<br>&gt; <br>&gt; // Fine<br>&gt; foo({ })<br>&gt; <br>&gt; // This fails with error:<br>&gt; //    call is to &#39;rethrows&#39; function,<br>&gt; //    but a defaulted argument function can throw<br>&gt; foo()<br>&gt; <br>&gt; Why should I have to write &quot;try foo()&quot;, shouldn&#39;t it take the default value (non throwing closure)?<br></p><p>This looks like a bug. We&#39;d appreciate a bug report on bugs.swift.org if you have some time.<br></p><p>-Joe<br></p></div></li></ul></li></ul></div>    </main>
    <script src="/js/app-c283ee129de63ad743722e9511e67a5d.js?vsn=d"></script>
  </body>
  <footer>
    <p>Swift and the Swift logo are trademarks of Apple Inc.</p>
  </footer>
</html>
